language: elixir

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.6.1
    - otp_release: 19.2
      elixir: 1.5.1
    - otp_release: 20.0
      elixir: 1.6.6
    - otp_release: 20.0
      elixir: 1.7.4

script:
  - "MIX_ENV=test mix do deps.get, test && mix credo && mix coveralls.travis"
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
